### ISSUE TITLE
dataset words repeat so many times.

### ISSUE THREAD

**Issue by Langjiaqi** [lancopku/SGM#11]
![repeat](https://user-images.githubusercontent.com/34952852/48715406-e8605900-ec4f-11e8-8ded-733aa2a7bbe3.PNG)
Is that normal?That  is definitely not a sentence.

**Comment by ypengc7512** [comment]
It's normal. The dataset I provided is the source dataset published by the author.

**Comment by Langjiaqi** [comment]
![image](https://user-images.githubusercontent.com/34952852/49012740-4d1e3500-f1b5-11e8-934c-e250f8fcdb01.png)

**Comment by Langjiaqi** [comment]
It's not correct English words, after running the preprocess.py, this picture just cut from save_data.src.dict.why?

**Comment by Langjiaqi** [comment]
Almost all the words is wrong, this dataset is official, why i have this problem, it's my encoding or decoding problems or in your computer it just like me. I can't understand the sentences and words is wrong, how can we predict it categories correctly?

**Comment by ypengc7512** [comment]
The download link for the RCV1-V2 official dataset is http://www.ai.mit.edu/projects/jmlr/papers/volume5/lewis04a/lyrl2004_rcv1v2_README.htm  You can download the source file yourself for processing. The dataset provided by the official website is the processed data, causing the words to be repeated many times so that they are not like a correct sentence.

**Comment by Langjiaqi** [comment]
OK, thank you!
